# Generated by Django 3.2.4 on 2021-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('student_name', models.CharField(max_length=150, null=True)),
                ('body_temp', models.FloatField(null=True)),
                ('attend_status', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'attendance_info',
            },
        ),
    ]
