# Generated by Django 3.2.4 on 2021-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_info',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance_info',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
