# Generated by Django 3.2.4 on 2021-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20210619_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstName', models.CharField(max_length=50)),
                ('student_LastName', models.CharField(max_length=50)),
                ('student_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'student_record',
            },
        ),
    ]
